import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import PersistentDrawerLeft from '../components/layout/PersistentDrawerLeft'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//export const revalidate = 0;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className={inter.className}>
        {/* <Link href="/">Home</Link>
        <Link href="/pessoa">Pessoas</Link> */}
        <PersistentDrawerLeft>
          {children}
        </PersistentDrawerLeft>
      </body>
    </html>
  )
}
